name: docker-prune

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 2 * * *"

jobs:
  docker-prune:
    uses: lrstanley/.github/.github/workflows/docker-prune.yml@master
    secrets:
      token: ${{ secrets.USER_PAT }}
