name: generate-readme

on:
  push:
    branches: [master]
    tags: [v*]
  schedule:
    - cron: "0 13 * * *"

jobs:
  generate:
    uses: lrstanley/.github/.github/workflows/generate-readme.yml@master
    secrets:
      token: ${{ secrets.USER_PAT }}
