name: test

on:
  pull_request:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  go-test:
    uses: lrstanley/.github/.github/workflows/lang-go-test-matrix.yml@master
    with:
      go-version: latest
      node-version: "17.9.0"
  go-lint:
    uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  docker-test:
    needs: [go-test, go-lint]
    uses: lrstanley/.github/.github/workflows/docker-release.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
